# Permalinks
permalink:        pretty

# Setup
title:            Flow UI Styleguide
tagline:          'Awesome Flow UI theme'
description:      'Styleguide for Electric Cloud Flow UI'
url:              https://github.com/electric-cloud/flow-styleguide
baseurl:          ''

github:
  url:            'https://electric-cloud.github.io/flow-styleguide/'

gems:
  - jekyll-paginate
  - jekyll-gist

collections:
  components:
    output: true

sass:
  sass_dir: _sass