- name: icon-menu-dropdown
  description: Dropdown menu arrow

- name: icon-application
  description: Application

- name: icon-project
  description: Project

- name: icon-component
  description: Application Component

- name: icon-process
  description: ( Needs to be contextual ) Application Process or Component Process

- name: icon-tier-map
  description: Tier Map

- name: icon-snapshot
  description: Snapshot

- name: icon-runtime-run
  description: ( Needs to be contexual ) Application Run or Pipeline Run or Release Run

- name: icon-row-collapse
  description: Collapse Row

- name: icon-row-expand
  description: Expand Row

- name: icon-go-to-details
  description: Go to item Details

- name: icon-runtime-status-success
  description: Success Status

- name: icon-runtime-duration
  description: Time Elaspsed

- name: icon-runtime-status-running
  description: Running Status

- name: icon-runtime-status-flagged
  description: Warning Status

- name: icon-runtime-status-aborted
  description: Aborted Status

- name: icon-runtime-status-failed
  description: Failed Status

- name: icon-runtime-status-waiting
  description: Waiting Status

- name: icon-environments-static
  description: Static Environment

- name: icon-manual-response-alert
  description: User Response

- name: icon-change-history
  description: Change History

- name: icon-runtime-duration
  description: ( Duplicated above )

- name: icon-mastercomponent
  description: Master Component

- name: icon-object-description
  description: Description

- name: icon-container
  description: Container

- name: button-delete
  description: Delete Selected Records

- name: button-add
  description: Add New
